### ISSUE TITLE
step of Download Open3D  failed

### ISSUE THREAD

**Issue by zuixiaosanlang** [pezcode/open3d-core-android#4]
i can download the code of open3d without using your scripts. 

but i do not how to change the cmakeList file and how to process Open3D-0.7.0.zip

can you help me ,

thanks

![image](https://user-images.githubusercontent.com/20105627/152756441-bb8c41da-857d-49b5-9344-58eeb643a55a.png)

**Comment by pezcode** [comment]
Not sure what's going wrong there 🤔 The Open3D account got renamed from `intel-isl` to `isl-org` but Github has a redirect which works for me.

Maybe try changing `intel-isl` to `isl-org` on this line in CMakeLists.txt:
https://github.com/pezcode/open3d-core-android/blob/3fdbc576ea91cc39a74a0a861f46d015c8a21db3/CMakeLists.txt#L53

Small side not: I haven't updated this repository in 3 years and version 0.7.0 is a little outdated

**Comment by zuixiaosanlang** [comment]
thanks, 
i solve this by change GIT_REPOSITORY path to which path i can download.
now it works, thank you
